'use client';

export interface ModelResponse {
  modelId: string;
  modelName: string;
  color: string;
  responses: { round: number; text: string; isInitial: boolean }[];
}

export interface GroupedAgreement {
  point: string;
  count: number;
  models: string[];
}

export interface DisagreementSide {
  position: string;
  models: string[];
}

export interface GroupedDisagreement {
  point: string;
  sides: DisagreementSide[];
}

export interface ConsensusResult {
  consensus_reached: boolean;
  consensus_type?: 'full' | 'partial' | 'none';
  similarity_score: number;
  synthesis?: string;
  syntheses?: { modelName: string; synthesis: string }[];
  camps?: { position: string; participants: string[] }[];
  key_agreements: GroupedAgreement[];
  key_disagreements: GroupedDisagreement[];
  closest_to_truth?: string;
  closest_to_truth_reason?: string;
  votes?: { yes: number; total: number; ratio: number };
  individual_votes?: { model: string; vote: string; score: number; reasoning: string }[];
}

export interface ReportData {
  question: string;
  date: string;
  iterations: number;
  models: ModelResponse[];
  consensusResult: ConsensusResult;
}

function generateMarkdown(data: ReportData): string {
  const lines: string[] = [];
  
  // Header
  lines.push('# 🎯 AI Roundtable Report');
  lines.push('');
  lines.push(`**Date:** ${data.date}`);
  lines.push(`**Rounds:** ${data.iterations}`);
  lines.push(`**Models:** ${data.models.map(m => m.modelName).join(', ')}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  
  // Question
  lines.push('## 📋 Question');
  lines.push('');
  lines.push(`> ${data.question}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  
  // Conclusion
  lines.push('## 🏁 Conclusion');
  lines.push('');
  
  const consensusEmoji = data.consensusResult.consensus_reached ? '✅' : '⚠️';
  const consensusText = data.consensusResult.consensus_reached ? 'Consensus Reached' : 'Positions Differ';
  lines.push(`### ${consensusEmoji} ${consensusText}`);
  lines.push(`**Agreement:** ${Math.round(data.consensusResult.similarity_score * 100)}%`);
  lines.push('');
  
  // Best answer
  if (data.consensusResult.closest_to_truth) {
    lines.push(`### 🏆 Best Initial Answer: **${data.consensusResult.closest_to_truth}**`);
    if (data.consensusResult.closest_to_truth_reason) {
      lines.push(`> ${data.consensusResult.closest_to_truth_reason}`);
    }
    lines.push('');
  }
  
  // Syntheses from models
  if (data.consensusResult.syntheses && data.consensusResult.syntheses.length > 0) {
    lines.push('### 📝 Model Syntheses');
    lines.push('');
    for (const s of data.consensusResult.syntheses) {
      lines.push(`**${s.modelName}:**`);
      lines.push(s.synthesis);
      lines.push('');
    }
  } else if (data.consensusResult.synthesis) {
    lines.push('### 📝 Synthesis');
    lines.push(data.consensusResult.synthesis);
    lines.push('');
  }
  
  // Agreements
  if (data.consensusResult.key_agreements?.length > 0) {
    lines.push('### ✅ All Agree');
    lines.push('');
    for (const agreement of data.consensusResult.key_agreements) {
      const modelsStr = agreement.models?.length > 0 ? ` (${agreement.models.join(', ')})` : '';
      lines.push(`- ${agreement.point}${modelsStr}`);
    }
    lines.push('');
  }
  
  // Disagreements
  if (data.consensusResult.key_disagreements?.length > 0) {
    lines.push('### ❌ Differences');
    lines.push('');
    for (const disagreement of data.consensusResult.key_disagreements) {
      lines.push(`- **${disagreement.point}**`);
      if (disagreement.sides?.length > 0) {
        for (const side of disagreement.sides) {
          lines.push(`  - ${side.models.join(', ')}: ${side.position}`);
        }
      }
    }
    lines.push('');
  }
  
  lines.push('---');
  lines.push('');
  
  // Discussion by Rounds (chronological order)
  lines.push('## 💬 Discussion');
  lines.push('');
  
  // Find max rounds across all models
  const maxRounds = Math.max(...data.models.map(m => m.responses.length));
  
  for (let round = 1; round <= maxRounds; round++) {
    const roundType = round === 1 ? 'Initial Positions' : `Round ${round} — Responses`;
    lines.push(`### 📍 ${roundType}`);
    lines.push('');
    
    for (const model of data.models) {
      const response = model.responses.find(r => r.round === round);
      if (response) {
        const isBest = data.consensusResult.closest_to_truth === model.modelName;
        const badge = isBest ? ' 🏆' : '';
        
        lines.push(`#### ${model.modelName}${badge}`);
        lines.push('');
        lines.push(response.text);
        lines.push('');
      }
    }
    
    lines.push('---');
    lines.push('');
  }
  
  // Footer
  lines.push(`*Generated by AI Roundtable | ${data.date}*`);
  
  return lines.join('\n');
}

export async function generatePDF(data: ReportData): Promise<Blob> {
  const markdown = generateMarkdown(data);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  return blob;
}

export function downloadPDF(blob: Blob, filename: string) {
  // Change extension to .md
  const mdFilename = filename.replace(/\.pdf$/i, '.md');
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = mdFilename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
